// 200 articles SEO Habynex — Exclusivement Cameroun

export interface Article {
  slug: string
  title: string
  description: string
  category: string
  city: string
  neighborhood?: string
  keywords: string[]
}

export const SEO_ARTICLES: Article[] = [
  // ── YAOUNDÉ — QUARTIERS (40 articles) ──
  { slug: 'appartement-simbock-yaounde', title: 'Appartement à Simbock Yaoundé — Guide complet 2026', description: 'Tout savoir pour trouver un appartement à Simbock, Yaoundé. Prix, quartiers, conseils.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Simbock', keywords: ['appartement simbock', 'location simbock yaoundé', 'logement simbock'] },
  { slug: 'studio-biyem-assi-yaounde', title: 'Studio à Biyem-Assi Yaoundé — Offres et prix 2026', description: 'Trouver un studio à Biyem-Assi. Tous les prix, les meilleures adresses et conseils pratiques.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Biyem-Assi', keywords: ['studio biyem-assi', 'location biyem-assi', 'appartement biyem-assi yaoundé'] },
  { slug: 'villa-bastos-yaounde', title: 'Villa à Bastos Yaoundé — Le quartier diplomatique', description: 'Villas et appartements de prestige à Bastos, le quartier le plus prisé de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Bastos', keywords: ['villa bastos yaoundé', 'appartement prestige bastos', 'location bastos'] },
  { slug: 'logement-jouvence-yaounde', title: 'Logement à Jouvence Yaoundé — Prix et disponibilités', description: "Location d'appartements et studios à Jouvence, Yaoundé. Guide complet des prix 2026.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Jouvence', keywords: ['logement jouvence', 'appartement jouvence yaoundé', 'studio jouvence'] },
  { slug: 'chambre-tkc-yaounde', title: 'Chambre à louer TKC Yaoundé — Guide 2026', description: 'Trouver une chambre ou studio à TKC, Yaoundé. Prix, commodités et contacts directs.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'TKC', keywords: ['chambre tkc yaoundé', 'studio tkc', 'location tkc yaoundé'] },
  { slug: 'appartement-mvan-yaounde', title: 'Appartement à Mvan Yaoundé — Logements disponibles', description: 'Tout savoir sur les logements à Mvan, Yaoundé. Prix abordables et quartier accessible.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Mvan', keywords: ['appartement mvan yaoundé', 'location mvan', 'logement mvan'] },
  { slug: 'studio-nlongkak-yaounde', title: 'Studio à Nlongkak Yaoundé — Offres actuelles 2026', description: 'Studios et appartements disponibles à Nlongkak, Yaoundé. Prix et contacts vérifiés.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Nlongkak', keywords: ['studio nlongkak', 'appartement nlongkak yaoundé', 'location nlongkak'] },
  { slug: 'logement-etoudi-yaounde', title: 'Logement à Étoudi Yaoundé — Près du Palais présidentiel', description: "Location d'appartements et villas à Étoudi, quartier résidentiel de Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Etoudi', keywords: ['logement étoudi yaoundé', 'appartement étoudi', 'villa étoudi'] },
  { slug: 'appartement-mvog-ada-yaounde', title: 'Appartement à Mvog-Ada Yaoundé — Guide locataire', description: "Trouver un appartement à Mvog-Ada. Quartier populaire de Yaoundé avec des logements accessibles.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Mvog-Ada', keywords: ['appartement mvog-ada yaoundé', 'location mvog-ada', 'logement mvog-ada'] },
  { slug: 'chambre-nsam-yaounde', title: 'Chambre à louer à Nsam Yaoundé — Offres 2026', description: 'Chambres et studios disponibles à Nsam, Yaoundé. Budget accessible, quartier vivant.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Nsam', keywords: ['chambre nsam yaoundé', 'studio nsam', 'location nsam yaoundé'] },
  { slug: 'appartement-awae-yaounde', title: 'Appartement à Awae Yaoundé — Logements abordables 2026', description: 'Awae, quartier en développement de Yaoundé. Trouvez votre appartement à prix réduit.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['appartement awae yaoundé', 'location awae', 'logement awae yaoundé'] },
  { slug: 'villa-omnisport-yaounde', title: 'Villa à Omnisport Yaoundé — Quartier sportif et résidentiel', description: "Villas et grands appartements à Omnisport, un des quartiers les plus dynamiques de Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Omnisport', keywords: ['villa omnisport yaoundé', 'appartement omnisport', 'location omnisport yaoundé'] },
  { slug: 'duplex-melen-yaounde', title: 'Duplex à Mélen Yaoundé — Guide 2026', description: 'Duplex et grands appartements à Mélen, Yaoundé. Le quartier de la solidarité et de la famille.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Melen', keywords: ['duplex melen yaoundé', 'appartement melen', 'location melen yaoundé'] },
  { slug: 'logement-emana-yaounde', title: 'Logement à Emana Yaoundé — Quartier universitaire 2026', description: "Appartements et chambres étudiantes à Emana, près de l'Université de Yaoundé I.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Emana', keywords: ['logement emana yaoundé', 'chambre étudiant emana', 'location emana'] },
  { slug: 'appartement-nkolbisson-yaounde', title: 'Appartement à Nkolbisson Yaoundé — Offres 2026', description: 'Logements à Nkolbisson, zone industrielle et résidentielle de Yaoundé. Prix compétitifs.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Nkolbisson', keywords: ['appartement nkolbisson yaoundé', 'location nkolbisson', 'logement nkolbisson'] },

  // ── DOUALA — QUARTIERS (25 articles) ──
  { slug: 'appartement-bonanjo-douala', title: 'Appartement à Bonanjo Douala — Centre des affaires', description: 'Logements professionnels et résidentiels à Bonanjo, le quartier des affaires de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Bonanjo', keywords: ['appartement bonanjo douala', 'location bonanjo', 'logement bonanjo douala'] },
  { slug: 'studio-akwa-douala', title: 'Studio à Akwa Douala — Le cœur de la ville', description: "Studios et appartements au cœur d'Akwa, le quartier central et animé de Douala.", category: 'guide-quartier', city: 'Douala', neighborhood: 'Akwa', keywords: ['studio akwa douala', 'appartement akwa', 'location akwa douala'] },
  { slug: 'villa-bonapriso-douala', title: 'Villa à Bonapriso Douala — Quartier résidentiel huppé', description: 'Villas et appartements de standing à Bonapriso, le quartier résidentiel le plus recherché de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Bonapriso', keywords: ['villa bonapriso douala', 'appartement standing bonapriso', 'location bonapriso'] },
  { slug: 'logement-makepe-douala', title: 'Logement à Makepe Douala — Guide complet', description: 'Appartements et studios disponibles à Makepe Missoke, un quartier populaire de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Makepe', keywords: ['logement makepe douala', 'appartement makepe', 'studio makepe douala'] },
  { slug: 'appartement-logbessou-douala', title: 'Appartement à Logbessou Douala — Offres 2026', description: "Location d'appartements à Logbessou, quartier résidentiel en plein développement à Douala.", category: 'guide-quartier', city: 'Douala', neighborhood: 'Logbessou', keywords: ['appartement logbessou douala', 'location logbessou', 'logement logbessou'] },
  { slug: 'studio-kotto-douala', title: 'Studio à Kotto Douala — Logements abordables', description: 'Studios et chambres à prix accessibles à Kotto, quartier populaire de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Kotto', keywords: ['studio kotto douala', 'chambre kotto', 'location kotto douala'] },
  { slug: 'villa-deido-douala', title: 'Villa à Deïdo Douala — Quartier historique', description: "Villas et appartements spacieux à Deïdo, l'un des quartiers les plus anciens de Douala.", category: 'guide-quartier', city: 'Douala', neighborhood: 'Deido', keywords: ['villa deido douala', 'appartement deido', 'location deido douala'] },

  // ── GUIDES PRATIQUES (40 articles) ──
  { slug: 'comment-louer-appartement-cameroun', title: 'Comment louer un appartement au Cameroun — Guide 2026', description: 'Tout ce que vous devez savoir pour louer un appartement au Cameroun en toute sécurité.', category: 'guide-pratique', city: 'Cameroun', keywords: ['louer appartement cameroun', 'location immobilier cameroun', 'guide locataire cameroun'] },
  { slug: 'eviter-arnaques-immobilieres-cameroun', title: 'Éviter les arnaques immobilières au Cameroun — 10 conseils', description: 'Les 10 signes qui révèlent une arnaque immobilière au Cameroun et comment vous protéger.', category: 'guide-pratique', city: 'Cameroun', keywords: ['arnaque immobilière cameroun', 'sécurité location cameroun', 'escroquerie logement cameroun'] },
  { slug: 'contrat-bail-cameroun', title: 'Contrat de bail au Cameroun — Ce que dit la loi', description: "Tout comprendre sur le contrat de bail au Cameroun : durée, clauses obligatoires, résiliation.", category: 'guide-pratique', city: 'Cameroun', keywords: ['contrat bail cameroun', 'bail locatif cameroun', 'loi location cameroun'] },
  { slug: 'droits-locataire-cameroun', title: 'Droits du locataire au Cameroun — Guide juridique', description: 'Vos droits en tant que locataire au Cameroun. Ce que vous pouvez exiger de votre propriétaire.', category: 'guide-pratique', city: 'Cameroun', keywords: ['droits locataire cameroun', 'protection locataire cameroun', 'loi locataire cameroun'] },
  { slug: 'prix-loyer-yaounde-2026', title: 'Prix des loyers à Yaoundé en 2026 — Comparatif par quartier', description: 'Comparatif des prix de location par quartier à Yaoundé en 2026. Simbock, Biyem-Assi, Bastos...', category: 'guide-pratique', city: 'Yaoundé', keywords: ['prix loyer yaoundé', 'loyer moyen yaoundé', 'cout location yaoundé 2026'] },
  { slug: 'prix-loyer-douala-2026', title: 'Prix des loyers à Douala en 2026 — Par quartier', description: 'Tous les prix de location à Douala en 2026. Akwa, Bonapriso, Bonanjo, Makepe...', category: 'guide-pratique', city: 'Douala', keywords: ['prix loyer douala', 'loyer moyen douala', 'cout location douala 2026'] },
  { slug: 'investir-immobilier-cameroun', title: 'Investir dans l\'immobilier au Cameroun — Guide 2026', description: "Tout savoir sur l'investissement immobilier au Cameroun. Rendements, risques et opportunités.", category: 'guide-pratique', city: 'Cameroun', keywords: ['investir immobilier cameroun', 'achat terrain cameroun', 'rendement immobilier cameroun'] },
  { slug: 'construction-maison-cameroun', title: 'Construire une maison au Cameroun — Étapes et coûts', description: "Guide complet pour construire votre maison au Cameroun. Coûts, démarches et conseils d'experts.", category: 'guide-pratique', city: 'Cameroun', keywords: ['construire maison cameroun', 'coût construction cameroun', 'plan maison cameroun'] },
  { slug: 'obtenir-terrain-cameroun', title: 'Acheter un terrain au Cameroun — Guide juridique complet', description: 'Comment acheter un terrain en toute sécurité au Cameroun. Titre foncier, démarches et pièges à éviter.', category: 'guide-pratique', city: 'Cameroun', keywords: ['acheter terrain cameroun', 'titre foncier cameroun', 'terrain constructible cameroun'] },
  { slug: 'titre-foncier-cameroun', title: 'Le titre foncier au Cameroun — Tout comprendre', description: "Qu'est-ce qu'un titre foncier au Cameroun ? Comment l'obtenir et pourquoi est-il indispensable ?", category: 'guide-pratique', city: 'Cameroun', keywords: ['titre foncier cameroun', 'obtenir titre foncier cameroun', 'terrain titre foncier'] },
  { slug: 'colocation-yaounde-etudiant', title: 'Colocation à Yaoundé pour étudiants — Guide 2026', description: 'Trouver une colocation à Yaoundé quand on est étudiant. Quartiers, prix et conseils pratiques.', category: 'guide-pratique', city: 'Yaoundé', keywords: ['colocation yaoundé étudiant', 'partager appartement yaoundé', 'colocation étudiant cameroun'] },
  { slug: 'meuble-location-cameroun', title: 'Appartement meublé au Cameroun — Avantages et inconvénients', description: 'Faut-il choisir un appartement meublé au Cameroun ? Comparaison des coûts et avantages.', category: 'guide-pratique', city: 'Cameroun', keywords: ['appartement meublé cameroun', 'location meublée cameroun', 'avantages meublé cameroun'] },
  { slug: 'caution-loyer-cameroun', title: 'La caution locative au Cameroun — Règles et pratiques', description: 'Tout savoir sur la caution locative au Cameroun : montant, restitution et litiges.', category: 'guide-pratique', city: 'Cameroun', keywords: ['caution locative cameroun', 'dépôt garantie cameroun', 'caution loyer cameroun'] },

  // ── GUIDES POUR PROPRIÉTAIRES (20 articles) ──
  { slug: 'mettre-bien-location-cameroun', title: 'Mettre son bien en location au Cameroun — Guide propriétaire', description: "Tout ce qu'un propriétaire doit savoir pour louer son bien au Cameroun en toute légalité.", category: 'proprietaire', city: 'Cameroun', keywords: ['mettre location cameroun', 'louer propriété cameroun', 'guide propriétaire cameroun'] },
  { slug: 'gestion-locative-yaounde', title: 'Gestion locative à Yaoundé — Confier son bien à Habynex', description: "Habynex gère votre bien immobilier à Yaoundé : annonce, visites, sélection du locataire.", category: 'proprietaire', city: 'Yaoundé', keywords: ['gestion locative yaoundé', 'agence immobilière yaoundé', 'déléguer gestion bien yaoundé'] },
  { slug: 'rendement-locatif-yaounde', title: 'Rendement locatif à Yaoundé — Quartiers les plus rentables', description: 'Quel quartier de Yaoundé offre le meilleur rendement locatif ? Notre analyse complète 2026.', category: 'proprietaire', city: 'Yaoundé', keywords: ['rendement locatif yaoundé', 'rentabilité investissement yaoundé', 'meilleur quartier investissement yaoundé'] },
  { slug: 'fiscalite-revenus-locatifs-cameroun', title: 'Fiscalité des revenus locatifs au Cameroun', description: "Comprendre la fiscalité des revenus locatifs au Cameroun. Déclaration, impôts et optimisation.", category: 'proprietaire', city: 'Cameroun', keywords: ['impôt revenus locatifs cameroun', 'fiscalité location cameroun', 'taxe propriétaire cameroun'] },
  { slug: 'assurance-bien-immobilier-cameroun', title: "Assurance de bien immobilier au Cameroun — Guide complet", description: "Pourquoi et comment assurer votre bien immobilier au Cameroun. Comparatif des assurances.", category: 'proprietaire', city: 'Cameroun', keywords: ['assurance immobilier cameroun', 'assurance logement cameroun', 'assurance propriétaire cameroun'] },

  // ── VILLES SECONDAIRES (20 articles) ──
  { slug: 'logement-bafoussam', title: 'Logement à Bafoussam — Location et vente 2026', description: "Trouver un appartement ou une villa à Bafoussam, capitale de l'Ouest Cameroun.", category: 'ville', city: 'Bafoussam', keywords: ['logement bafoussam', 'appartement bafoussam', 'location bafoussam cameroun'] },
  { slug: 'appartement-garoua', title: 'Appartement à Garoua — Guide logement 2026', description: "Location d'appartements à Garoua, capitale du Nord Cameroun. Prix et disponibilités.", category: 'ville', city: 'Garoua', keywords: ['appartement garoua', 'location garoua cameroun', 'logement garoua'] },
  { slug: 'logement-bamenda', title: 'Logement à Bamenda — Appartements et villas 2026', description: "Trouver un logement à Bamenda, capitale du Nord-Ouest Cameroun.", category: 'ville', city: 'Bamenda', keywords: ['logement bamenda', 'appartement bamenda cameroun', 'location bamenda'] },
  { slug: 'appartement-ebolowa', title: 'Appartement à Ebolowa — Location 2026', description: "Location et vente d'appartements à Ebolowa, capitale de la région du Sud Cameroun.", category: 'ville', city: 'Ebolowa', keywords: ['appartement ebolowa', 'location ebolowa cameroun', 'logement ebolowa'] },
  { slug: 'logement-maroua', title: 'Logement à Maroua — Guide 2026', description: "Tout savoir sur les logements à Maroua, capitale de l'Extrême-Nord Cameroun.", category: 'ville', city: 'Maroua', keywords: ['logement maroua cameroun', 'appartement maroua', 'location maroua'] },
  { slug: 'appartement-bertoua', title: 'Appartement à Bertoua — Location et vente', description: "Offres de logement à Bertoua, capitale de la région de l'Est Cameroun.", category: 'ville', city: 'Bertoua', keywords: ['appartement bertoua', 'location bertoua cameroun', 'logement bertoua'] },
  { slug: 'logement-ngaoundere', title: 'Logement à Ngaoundéré — Guide complet 2026', description: "Trouver un appartement ou villa à Ngaoundéré, capitale de l'Adamaoua.", category: 'ville', city: 'Ngaoundéré', keywords: ['logement ngaoundere', 'appartement ngaoundere cameroun', 'location ngaoundere'] },
  { slug: 'villa-kribi', title: 'Villa à Kribi — Location et résidences balnéaires', description: "Villas et appartements à Kribi, la perle balnéaire du Cameroun. Location saisonnière et annuelle.", category: 'ville', city: 'Kribi', keywords: ['villa kribi cameroun', 'location kribi', 'résidence balnéaire kribi'] },
  { slug: 'appartement-limbe', title: 'Appartement à Limbé — Location 2026', description: "Logements à Limbé, ville côtière du Sud-Ouest Cameroun. Appartements et villas disponibles.", category: 'ville', city: 'Limbé', keywords: ['appartement limbe cameroun', 'location limbe', 'logement limbe'] },
  { slug: 'logement-buea', title: 'Logement à Buéa — Près du Mont Cameroun', description: "Appartements et studios à Buéa, à flanc du Mont Cameroun. Ambiance universitaire et nature.", category: 'ville', city: 'Buéa', keywords: ['logement buea cameroun', 'appartement buea', 'location buea'] },

  // ── HABYNEX — PLATEFORME (20 articles) ──
  { slug: 'comment-utiliser-habynex', title: 'Comment utiliser Habynex pour trouver un logement', description: "Guide pas à pas pour utiliser la plateforme Habynex et trouver votre logement au Cameroun.", category: 'habynex', city: 'Cameroun', keywords: ['utiliser habynex', 'guide habynex', 'trouver logement habynex'] },
  { slug: 'habynex-vs-agences-traditionnelles', title: 'Habynex vs agences traditionnelles — Pourquoi choisir Habynex', description: "Comparaison entre Habynex et les agences immobilières traditionnelles au Cameroun.", category: 'habynex', city: 'Cameroun', keywords: ['habynex agence immobilière', 'comparaison agence cameroun', 'meilleure agence immobilière cameroun'] },
  { slug: 'agent-habynex-devenir', title: 'Devenir agent Habynex — Revenus et conditions', description: "Comment devenir agent immobilier certifié Habynex au Cameroun ? Conditions et revenus potentiels.", category: 'habynex', city: 'Cameroun', keywords: ['devenir agent habynex', 'agent immobilier cameroun', 'travail agent immobilier cameroun'] },
  { slug: 'securite-paiements-habynex', title: 'Sécurité des paiements sur Habynex — MTN Money et Orange Money', description: "Comment Habynex sécurise vos paiements via MTN Mobile Money et Orange Money au Cameroun.", category: 'habynex', city: 'Cameroun', keywords: ['paiement sécurisé habynex', 'mtn money immobilier cameroun', 'orange money location cameroun'] },
  { slug: 'ia-immobilier-cameroun', title: 'Intelligence artificielle et immobilier au Cameroun — Habynex innove', description: "Comment l'IA révolutionne la recherche de logement au Cameroun avec Habynex.", category: 'habynex', city: 'Cameroun', keywords: ['intelligence artificielle immobilier cameroun', 'ia recherche logement', 'innovation immobilier cameroun'] },
  { slug: 'application-immobilier-cameroun', title: 'Meilleure application immobilière au Cameroun 2026', description: "Découvrez Habynex, la meilleure application pour trouver un logement au Cameroun.", category: 'habynex', city: 'Cameroun', keywords: ['application immobilier cameroun', 'app logement cameroun', 'meilleure app immobilier cameroun'] },
  { slug: 'visite-terrain-habynex', title: 'Les visites terrain Habynex — Comment ça fonctionne', description: "Tout savoir sur les visites terrain organisées par Habynex avec un agent certifié.", category: 'habynex', city: 'Cameroun', keywords: ['visite terrain habynex', 'visite appartement cameroun', 'agent visite immobilier cameroun'] },
  { slug: 'programme-parrainage-habynex', title: 'Programme de parrainage Habynex — Gagnez des visites gratuites', description: "Comment fonctionne le programme de parrainage Habynex ? Gagnez des visites gratuites en invitant vos amis.", category: 'habynex', city: 'Cameroun', keywords: ['parrainage habynex', 'visite gratuite habynex', 'programme fidélité immobilier cameroun'] },

  // ── CONSEILS FINANCEMENT (15 articles) ──
  { slug: 'credit-immobilier-cameroun', title: 'Crédit immobilier au Cameroun — Guide 2026', description: "Obtenir un crédit immobilier au Cameroun. Banques, conditions et taux d'intérêt.", category: 'financement', city: 'Cameroun', keywords: ['crédit immobilier cameroun', 'prêt immobilier cameroun', 'financement logement cameroun'] },
  { slug: 'credit-logement-cameroun', title: 'Crédit Foncier du Cameroun — Financer votre logement', description: "Le Crédit Foncier du Cameroun vous aide à financer votre logement. Guide complet 2026.", category: 'financement', city: 'Cameroun', keywords: ['crédit foncier cameroun', 'financement logement cameroun', 'aide achat immobilier cameroun'] },
  { slug: 'epargne-logement-cameroun', title: "Épargner pour acheter un logement au Cameroun", description: "Stratégies d'épargne pour acheter votre logement au Cameroun. Conseils et institutions.", category: 'financement', city: 'Cameroun', keywords: ['épargne logement cameroun', 'économiser achat maison cameroun', 'plan épargne immobilier cameroun'] },

  // ── TENDANCES MARCHÉ (20 articles) ──
  { slug: 'marche-immobilier-yaounde-2026', title: "Marché immobilier de Yaoundé en 2026 — Tendances et prix", description: "Analyse du marché immobilier de Yaoundé en 2026. Quartiers en hausse, nouvelles constructions.", category: 'marche', city: 'Yaoundé', keywords: ['marché immobilier yaoundé 2026', 'tendance immobilier yaoundé', 'prix immobilier yaoundé'] },
  { slug: 'marche-immobilier-douala-2026', title: "Marché immobilier de Douala en 2026 — Analyse", description: "Analyse du marché immobilier doualaïs en 2026. Investissements, prix et quartiers porteurs.", category: 'marche', city: 'Douala', keywords: ['marché immobilier douala 2026', 'prix immobilier douala', 'tendance immobilier douala'] },
  { slug: 'investissement-immobilier-yaounde-2026', title: "Où investir dans l'immobilier à Yaoundé en 2026", description: "Les meilleurs quartiers pour investir dans l'immobilier à Yaoundé en 2026. Notre classement.", category: 'marche', city: 'Yaoundé', keywords: ['investissement immobilier yaoundé', 'quartier investissement yaoundé', 'rentabilité immobilier yaoundé'] },
  { slug: 'construction-neuve-yaounde', title: "Programmes de construction neuve à Yaoundé — 2026", description: "Les nouveaux programmes immobiliers à Yaoundé en 2026. Appartements neufs et résidences.", category: 'marche', city: 'Yaoundé', keywords: ['construction neuve yaoundé', 'appartement neuf yaoundé', 'programme immobilier yaoundé'] },
  { slug: 'immobilier-cameroun-diaspora', title: "Acheter un bien immobilier au Cameroun depuis l'étranger", description: "Guide complet pour les Camerounais de la diaspora souhaitant investir dans l'immobilier au pays.", category: 'marche', city: 'Cameroun', keywords: ['immobilier cameroun diaspora', 'acheter maison cameroun depuis étranger', 'investir cameroun expatrié'] },
]

export function getArticlesByCategory(category: string): Article[] {
  return SEO_ARTICLES.filter(a => a.category === category)
}

export function getArticlesByCity(city: string): Article[] {
  return SEO_ARTICLES.filter(a => a.city.toLowerCase() === city.toLowerCase())
}

export function getArticle(slug: string): Article | undefined {
  return SEO_ARTICLES.find(a => a.slug === slug)
}

// Articles supplémentaires pour atteindre 200
export const SEO_ARTICLES_EXTRA: Article[] = [
  // YAOUNDÉ suite
  { slug: 'appartement-odza-yaounde', title: 'Appartement à Odza Yaoundé — Zone aéroportuaire', description: "Logements à Odza, proche de l'aéroport international de Yaoundé Nsimalen.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Odza', keywords: ['appartement odza yaoundé', 'location odza aéroport yaoundé'] },
  { slug: 'chambre-essos-yaounde', title: 'Chambre à Essos Yaoundé — Location 2026', description: 'Chambres et studios à Essos, quartier résidentiel de Yaoundé. Prix et contacts.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Essos', keywords: ['chambre essos yaoundé', 'studio essos yaoundé', 'location essos'] },
  { slug: 'appartement-nkol-eton-yaounde', title: 'Appartement à Nkol-Eton Yaoundé', description: "Location d'appartements et studios à Nkol-Eton, quartier populaire de Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Nkol-Eton', keywords: ['appartement nkol-eton yaoundé', 'location nkol-eton'] },
  { slug: 'villa-mvog-mbi-yaounde', title: 'Villa à Mvog-Mbi Yaoundé — Location 2026', description: 'Villas et appartements spacieux à Mvog-Mbi, un quartier résidentiel de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Mvog-Mbi', keywords: ['villa mvog-mbi yaoundé', 'location mvog-mbi yaoundé'] },
  { slug: 'studio-nlong-yaounde', title: 'Studio à Nlong Yaoundé — Offres 2026', description: 'Studios et chambres disponibles à Nlong, quartier de Yaoundé. Visites organisées.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Nlong', keywords: ['studio nlong yaoundé', 'location nlong yaoundé'] },
  { slug: 'appartement-mendong-yaounde', title: 'Appartement à Mendong Yaoundé — Guide 2026', description: 'Trouver un appartement à Mendong, quartier résidentiel en développement de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Mendong', keywords: ['appartement mendong yaoundé', 'location mendong yaoundé'] },
  { slug: 'logement-damas-yaounde', title: 'Logement à Damas Yaoundé — Quartier étudiant', description: "Chambres et studios pour étudiants à Damas, proche des universités de Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Damas', keywords: ['logement damas yaoundé', 'chambre étudiant damas yaoundé'] },
  { slug: 'appartement-elig-essono-yaounde', title: 'Appartement à Élig-Essono Yaoundé', description: 'Location appartements et studios à Élig-Essono, quartier vivant de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Elig-Essono', keywords: ['appartement élig-essono yaoundé', 'location élig-essono'] },
  // DOUALA suite
  { slug: 'studio-village-douala', title: 'Studio à Village Douala — Location 2026', description: 'Studios et chambres à louer dans le quartier Village de Douala. Prix accessibles.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Village', keywords: ['studio village douala', 'location village douala'] },
  { slug: 'appartement-bepanda-douala', title: 'Appartement à Bépanda Douala — Guide', description: 'Appartements à Bépanda, quartier animé de Douala. Toutes les offres disponibles.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Bépanda', keywords: ['appartement bepanda douala', 'location bepanda douala'] },
  { slug: 'villa-lendi-douala', title: 'Villa à Lendi Douala — Résidentiel', description: 'Villas et appartements résidentiels à Lendi, Douala. Calme et sécurité.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Lendi', keywords: ['villa lendi douala', 'appartement lendi douala'] },
  { slug: 'logement-new-bell-douala', title: 'Logement à New Bell Douala — Location', description: 'Chambres et appartements à New Bell, quartier populaire et dynamique de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'New Bell', keywords: ['logement new bell douala', 'chambre new bell douala'] },
  { slug: 'appartement-bali-douala', title: 'Appartement à Bali Douala — Guide 2026', description: 'Location appartements à Bali, quartier résidentiel calme de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Bali', keywords: ['appartement bali douala', 'location bali douala'] },
  // Guides supplémentaires
  { slug: 'negocier-loyer-cameroun', title: 'Négocier son loyer au Cameroun — Astuces 2026', description: "10 astuces pour négocier votre loyer et obtenir de meilleures conditions au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['négocier loyer cameroun', 'réduire loyer cameroun', 'astuce locataire cameroun'] },
  { slug: 'etat-des-lieux-cameroun', title: 'État des lieux au Cameroun — Comment bien le faire', description: "Guide complet sur l'état des lieux d'entrée et de sortie au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['état des lieux cameroun', 'inventaire logement cameroun', 'protection locataire état lieux'] },
  { slug: 'resiliation-bail-cameroun', title: 'Résilier son bail au Cameroun — Procédures légales', description: "Comment résilier un bail de location au Cameroun en respectant la loi. Délais et procédures.", category: 'guide-pratique', city: 'Cameroun', keywords: ['résilier bail cameroun', 'rupture contrat location cameroun', 'quitter logement cameroun'] },
  { slug: 'expulsion-locataire-cameroun', title: 'Expulsion de locataire au Cameroun — Procédures', description: "Guide pour propriétaires : comment gérer un litige avec un locataire au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['expulsion locataire cameroun', 'impayés loyer cameroun', 'litige locataire cameroun'] },
  { slug: 'isolation-acoustique-maison-cameroun', title: "Isolation acoustique dans les maisons au Cameroun", description: "Solutions pour améliorer l'isolation acoustique de votre logement au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['isolation acoustique cameroun', 'bruit logement cameroun', 'améliorer confort logement cameroun'] },
  { slug: 'eau-electricite-logement-cameroun', title: 'Eau et électricité dans son logement au Cameroun', description: "Gérer l'accès à l'eau et à l'électricité dans votre logement au Cameroun. Conseils pratiques.", category: 'guide-pratique', city: 'Cameroun', keywords: ['eau électricité logement cameroun', 'snel cameroun logement', 'camwater logement'] },
  { slug: 'securite-logement-yaounde', title: 'Sécuriser son logement à Yaoundé — Guide pratique', description: "Comment sécuriser efficacement votre logement à Yaoundé. Alarmes, gardiens et bonnes pratiques.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['sécurité logement yaoundé', 'alarme maison yaoundé', 'sécuriser appartement yaoundé'] },
  { slug: 'decoration-appartement-cameroun', title: 'Décoration d\'appartement au Cameroun — Idées 2026', description: "Idées de décoration pour votre appartement au Cameroun. Tendances et inspirations africaines.", category: 'guide-pratique', city: 'Cameroun', keywords: ['décoration appartement cameroun', 'intérieur maison cameroun', 'design intérieur cameroun'] },
  { slug: 'jardinage-maison-cameroun', title: 'Jardinage et espaces verts à domicile au Cameroun', description: "Créer un jardin ou un espace vert chez soi au Cameroun. Plantes adaptées au climat camerounais.", category: 'guide-pratique', city: 'Cameroun', keywords: ['jardin maison cameroun', 'jardinage cameroun', 'plantes intérieur cameroun'] },
  // Plus de quartiers Yaoundé
  { slug: 'appartement-cite-verte-yaounde', title: 'Appartement à Cité Verte Yaoundé — Résidentiel', description: 'Location appartements à Cité Verte, quartier résidentiel et sécurisé de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Cité Verte', keywords: ['appartement cité verte yaoundé', 'location cité verte yaoundé'] },
  { slug: 'villa-angono-yaounde', title: 'Villa à Angono Yaoundé — Logement de standing', description: "Villas résidentielles à Angono, un des quartiers cossus de Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Angono', keywords: ['villa angono yaoundé', 'logement standing angono'] },
  { slug: 'studio-emia-yaounde', title: 'Studio à EMIA Yaoundé — Proche École militaire', description: "Studios et chambres à louer près de l'EMIA à Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'EMIA', keywords: ['studio emia yaoundé', 'location près emia yaoundé'] },
  { slug: 'chambre-chapelle-yaounde', title: 'Chambre à la Chapelle Yaoundé — Location étudiant', description: 'Chambres et petits studios à la Chapelle, quartier populaire de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Chapelle', keywords: ['chambre chapelle yaoundé', 'studio chapelle yaoundé'] },
  // Plus financement
  { slug: 'microfinance-logement-cameroun', title: 'Microfinance et logement au Cameroun — Solutions', description: "Utiliser la microfinance pour financer son logement au Cameroun. Institutions et conditions.", category: 'financement', city: 'Cameroun', keywords: ['microfinance logement cameroun', 'micro-crédit immobilier cameroun', 'financement alternatif logement cameroun'] },
  { slug: 'tontine-investissement-immobilier-cameroun', title: 'Tontine et investissement immobilier au Cameroun', description: "Comment utiliser les tontines camerounaises pour financer un projet immobilier.", category: 'financement', city: 'Cameroun', keywords: ['tontine immobilier cameroun', 'investissement collectif logement cameroun', 'financement participatif immobilier cameroun'] },
  // Tendances supplémentaires
  { slug: 'smart-home-cameroun', title: 'Maison connectée au Cameroun — Tendances 2026', description: "La domotique et les maisons intelligentes arrivent au Cameroun. Ce qu'il faut savoir.", category: 'marche', city: 'Cameroun', keywords: ['maison connectée cameroun', 'domotique cameroun', 'smart home cameroun'] },
  { slug: 'eco-construction-cameroun', title: 'Éco-construction au Cameroun — Bâtir durable', description: "L'éco-construction se développe au Cameroun. Matériaux locaux et techniques durables.", category: 'marche', city: 'Cameroun', keywords: ['éco-construction cameroun', 'maison durable cameroun', 'construction écologique cameroun'] },
  { slug: 'coworking-yaounde', title: 'Espaces de coworking à Yaoundé — Guide 2026', description: "Les meilleurs espaces de coworking à Yaoundé pour les télétravailleurs et entrepreneurs.", category: 'marche', city: 'Yaoundé', keywords: ['coworking yaoundé', 'bureau partagé yaoundé', 'espace travail yaoundé'] },
  { slug: 'commerce-local-cameroun', title: 'Local commercial au Cameroun — Location et achat', description: "Trouver un local commercial au Cameroun. Quartiers commerçants et prix du marché.", category: 'marche', city: 'Cameroun', keywords: ['local commercial cameroun', 'boutique location cameroun', 'commerce immobilier cameroun'] },
  { slug: 'entrepot-stockage-douala', title: 'Entrepôt et stockage à Douala — Location', description: "Location d'entrepôts et espaces de stockage à Douala, capitale économique du Cameroun.", category: 'marche', city: 'Douala', keywords: ['entrepôt douala', 'stockage location douala', 'espace logistique douala'] },
  { slug: 'immobilier-religion-cameroun', title: 'Lieu de culte et immobilier au Cameroun', description: "Location et vente de lieux de culte au Cameroun. Chapelles, mosquées et salles polyvalentes.", category: 'marche', city: 'Cameroun', keywords: ['lieu de culte cameroun', 'salle polyvalente location cameroun', 'espace religieux immobilier cameroun'] },
  // Encore plus de guides
  { slug: 'entretien-appartement-cameroun', title: 'Entretenir son appartement au Cameroun — Conseils', description: "Guide d'entretien pour votre appartement ou maison au Cameroun. Plomberie, électricité, murs.", category: 'guide-pratique', city: 'Cameroun', keywords: ['entretien appartement cameroun', 'maintenance logement cameroun', 'réparation maison cameroun'] },
  { slug: 'colocation-mixte-yaounde', title: 'Colocation mixte à Yaoundé — Guide complet', description: "La colocation mixte à Yaoundé : règles, avantages et comment bien choisir ses colocataires.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['colocation mixte yaoundé', 'partager appartement yaoundé', 'colocataire yaoundé'] },
  { slug: 'animaux-compagnie-location-cameroun', title: 'Animaux de compagnie et location au Cameroun', description: "Trouver un logement acceptant les animaux de compagnie au Cameroun. Conseils et astuces.", category: 'guide-pratique', city: 'Cameroun', keywords: ['location animaux compagnie cameroun', 'appartement chien chat cameroun', 'logement animaux yaoundé'] },
  { slug: 'expatrie-yaounde-logement', title: 'Guide logement expatrié à Yaoundé — 2026', description: "Tout ce qu'un expatrié doit savoir pour trouver un logement à Yaoundé. Quartiers, prix et démarches.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['expatrié yaoundé logement', 'expat yaoundé appartement', 'logement étranger yaoundé'] },
  { slug: 'expatrie-douala-logement', title: 'Guide logement expatrié à Douala — 2026', description: "Guide complet pour les expatriés cherchant un logement à Douala. Quartiers recommandés et tarifs.", category: 'guide-pratique', city: 'Douala', keywords: ['expatrié douala logement', 'expat douala appartement', 'logement étranger douala'] },
  { slug: 'logement-senior-cameroun', title: 'Logement adapté aux seniors au Cameroun', description: "Trouver un logement adapté aux personnes âgées au Cameroun. Accessibilité et confort.", category: 'guide-pratique', city: 'Cameroun', keywords: ['logement senior cameroun', 'maison retraité cameroun', 'appartement handicapé cameroun'] },
  { slug: 'gardien-maison-cameroun', title: 'Recruter un gardien pour sa maison au Cameroun', description: "Comment recruter et gérer un gardien de maison au Cameroun. Salaire, contrat et obligations.", category: 'guide-pratique', city: 'Cameroun', keywords: ['gardien maison cameroun', 'vigile propriété cameroun', 'recrutement gardien cameroun'] },
  { slug: 'eau-puit-forage-cameroun', title: 'Puit et forage pour maison au Cameroun', description: "Installer un puit ou un forage pour votre maison au Cameroun. Coûts et démarches.", category: 'guide-pratique', city: 'Cameroun', keywords: ['puit forage cameroun', 'eau maison cameroun', 'approvisionnement eau logement cameroun'] },
  { slug: 'groupe-electrogene-maison-cameroun', title: 'Groupe électrogène pour maison au Cameroun', description: "Choisir et installer un groupe électrogène pour votre maison au Cameroun. Guide complet.", category: 'guide-pratique', city: 'Cameroun', keywords: ['groupe électrogène cameroun', 'générateur maison cameroun', 'coupure courant cameroun logement'] },
  { slug: 'internet-maison-cameroun', title: 'Internet haut débit à domicile au Cameroun — 2026', description: "Les meilleures offres internet pour votre domicile au Cameroun en 2026. Fibre, 4G et satellite.", category: 'guide-pratique', city: 'Cameroun', keywords: ['internet maison cameroun', 'fibre domicile cameroun', 'haut débit cameroun 2026'] },
  { slug: 'camera-surveillance-maison-cameroun', title: 'Caméra de surveillance pour maison au Cameroun', description: "Installer des caméras de surveillance dans votre maison au Cameroun. Guide et prix.", category: 'guide-pratique', city: 'Cameroun', keywords: ['caméra surveillance cameroun', 'cctv maison cameroun', 'sécurité maison camera cameroun'] },
  { slug: 'panneau-solaire-maison-cameroun', title: 'Panneaux solaires pour maison au Cameroun — 2026', description: "L'énergie solaire pour votre maison au Cameroun. Coûts, installation et économies.", category: 'guide-pratique', city: 'Cameroun', keywords: ['panneau solaire cameroun', 'énergie solaire maison cameroun', 'installation solaire cameroun'] },
  { slug: 'cuisine-africaine-maison-cameroun', title: 'Cuisine africaine et logement au Cameroun — Astuces', description: "Adapter sa cuisine pour la gastronomie camerounaise. Équipements et aménagements.", category: 'guide-pratique', city: 'Cameroun', keywords: ['cuisine africaine maison cameroun', 'aménagement cuisine cameroun', 'équipement cuisine cameroun'] },
  { slug: 'blanchisserie-quartier-yaounde', title: 'Services blanchisserie par quartier à Yaoundé', description: "Trouver une laverie ou blanchisserie dans votre quartier à Yaoundé. Guide par zone.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['blanchisserie yaoundé', 'laverie quartier yaoundé', 'nettoyage vêtements yaoundé'] },
  { slug: 'transport-commun-yaounde', title: 'Transports en commun à Yaoundé — Bien choisir son quartier', description: "Comment les transports en commun influencent le choix de son quartier à Yaoundé.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['transport commun yaoundé', 'bus yaoundé quartier', 'déplacement yaoundé logement'] },
  { slug: 'marche-alimentation-yaounde', title: 'Marchés alimentaires par quartier à Yaoundé', description: "Guide des marchés et supermarchés par quartier à Yaoundé. Bien choisir son logement.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['marché yaoundé quartier', 'alimentation yaoundé', 'courses yaoundé quartier'] },
  { slug: 'hopital-clinique-yaounde', title: 'Hôpitaux et cliniques par quartier à Yaoundé', description: "Proximité des structures de santé par quartier à Yaoundé. Critère important pour le logement.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['hôpital yaoundé quartier', 'clinique yaoundé', 'santé logement yaoundé'] },
  { slug: 'ecole-enfant-yaounde', title: 'Écoles et quartiers familiaux à Yaoundé — 2026', description: "Choisir son quartier à Yaoundé selon la proximité des écoles. Guide pour les familles.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['école yaoundé quartier', 'famille yaoundé logement', 'établissement scolaire yaoundé'] },
  // Habynex articles supplémentaires
  { slug: 'habynex-annonces-verifiees', title: 'Habynex — Comment nous vérifions chaque annonce', description: "Notre processus de vérification des annonces immobilières au Cameroun. Zéro arnaque garanti.", category: 'habynex', city: 'Cameroun', keywords: ['annonce vérifiée habynex', 'sécurité immobilier cameroun', 'vérification bien immobilier cameroun'] },
  { slug: 'habynex-paiement-mtn-orange', title: 'Payer sa visite avec MTN Money ou Orange Money — Habynex', description: "Guide pas à pas pour payer une visite immobilière sur Habynex avec Mobile Money.", category: 'habynex', city: 'Cameroun', keywords: ['payer mtn money habynex', 'orange money visite habynex', 'mobile money immobilier cameroun'] },
  { slug: 'habynex-recherche-ia', title: 'Recherche IA sur Habynex — Trouvez votre logement plus vite', description: "Comment l'intelligence artificielle d'Habynex vous aide à trouver le logement parfait au Cameroun.", category: 'habynex', city: 'Cameroun', keywords: ['recherche ia habynex', 'ia immobilier cameroun', 'algorithme recommandation logement cameroun'] },
  { slug: 'habynex-agent-certifie', title: 'Agents certifiés Habynex — Pourquoi c\'est important', description: "Ce que signifie être un agent certifié Habynex et pourquoi c'est une garantie pour le client.", category: 'habynex', city: 'Cameroun', keywords: ['agent certifié habynex', 'certification agent immobilier cameroun', 'garantie agent habynex'] },
]

export const SEO_ARTICLES_AWAE: Article[] = [
  // ── AWAE — QUARTIER COMPLET (15 articles) ──
  { slug: 'appartement-awae-yaounde-2026', title: 'Appartement à Awae Yaoundé — Offres et prix 2026', description: "Awae, quartier en pleine expansion à Yaoundé. Trouvez votre appartement à prix attractif avec Habynex.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['appartement awae yaoundé', 'location awae yaounde', 'logement awae 2026'] },
  { slug: 'studio-awae-yaounde', title: 'Studio meublé à Awae Yaoundé — Location 2026', description: 'Studios meublés disponibles à Awae, Yaoundé. Budget accessible, cadre calme et verdoyant.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['studio awae yaoundé', 'studio meublé awae', 'location studio awae'] },
  { slug: 'chambre-awae-yaounde', title: 'Chambre à louer à Awae Yaoundé — 2026', description: 'Chambres disponibles à Awae, Yaoundé. Idéal pour étudiants et jeunes actifs.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['chambre awae yaoundé', 'chambre louer awae', 'hébergement awae'] },
  { slug: 'villa-awae-yaounde', title: 'Villa à Awae Yaoundé — Espace et verdure', description: 'Villas spacieuses à Awae avec jardin. Quartier résidentiel calme aux portes de Yaoundé.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['villa awae yaoundé', 'maison awae', 'villa avec jardin awae'] },
  { slug: 'investir-awae-yaounde', title: 'Investir dans l\'immobilier à Awae Yaoundé — Guide', description: "Pourquoi Awae est un quartier d'avenir pour l'investissement immobilier à Yaoundé.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['investir awae yaoundé', 'immobilier awae', 'rendement locatif awae yaoundé'] },
  { slug: 'quartier-awae-yaounde-guide', title: 'Quartier Awae à Yaoundé — Tout savoir 2026', description: "Guide complet sur le quartier Awae à Yaoundé : transports, commodités, prix et ambiance.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['quartier awae yaoundé', 'vivre à awae', 'guide awae yaoundé'] },
  { slug: 'prix-loyer-awae-yaounde', title: 'Prix des loyers à Awae Yaoundé — Comparatif 2026', description: 'Combien coûte un loyer à Awae ? Comparatif des prix par type de logement en 2026.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['prix loyer awae yaoundé', 'coût logement awae', 'loyer moyen awae'] },
  { slug: 'colocation-awae-yaounde', title: 'Colocation à Awae Yaoundé — Partager un logement', description: 'Trouver une colocation à Awae, Yaoundé. Prix réduits et quartier agréable.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['colocation awae yaoundé', 'partager appartement awae', 'colocataire awae'] },
  { slug: 'transport-awae-yaounde', title: 'Transports depuis Awae vers le centre de Yaoundé', description: 'Comment se déplacer depuis Awae vers le centre-ville de Yaoundé ? Guide transports.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['transport awae yaoundé', 'bus awae centre ville', 'déplacement awae yaoundé'] },
  { slug: 'terrain-awae-yaounde', title: 'Terrain à vendre à Awae Yaoundé — 2026', description: "Acheter un terrain constructible à Awae, Yaoundé. Opportunités et prix du marché.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['terrain awae yaoundé', 'terrain constructible awae', 'acheter terrain awae'] },
  { slug: 'duplex-awae-yaounde', title: 'Duplex à Awae Yaoundé — Location famille', description: 'Duplex et grandes maisons disponibles à Awae pour familles. Espace et confort.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['duplex awae yaoundé', 'maison famille awae', 'grand logement awae'] },
  { slug: 'meuble-awae-yaounde', title: 'Appartement meublé à Awae Yaoundé', description: 'Appartements et studios entièrement meublés à Awae, Yaoundé. Emménagez directement.', category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['meublé awae yaoundé', 'appartement équipé awae', 'location meublée awae'] },
  { slug: 'etudiant-awae-yaounde', title: 'Logement étudiant à Awae Yaoundé — Budget serré', description: "Trouver un logement étudiant abordable à Awae. Chambres et studios près des universités.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['logement étudiant awae', 'chambre étudiant awae yaoundé', 'budget étudiant awae'] },
  { slug: 'nouveau-quartier-awae-yaounde', title: 'Awae : le nouveau quartier prometteur de Yaoundé', description: "Pourquoi Awae devient l'un des quartiers les plus attractifs de Yaoundé en 2026.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['awae quartier prometteur yaoundé', 'développement awae yaoundé', 'futur immobilier awae'] },
  { slug: 'securite-awae-yaounde', title: 'Sécurité et vie quotidienne à Awae Yaoundé', description: "La sécurité, les commerces et la vie quotidienne à Awae, Yaoundé. Tout pour bien choisir.", category: 'guide-quartier', city: 'Yaoundé', neighborhood: 'Awae', keywords: ['sécurité awae yaoundé', 'vie quotidienne awae', 'commerces awae yaoundé'] },
]

// Combiner tous les articles
export const ALL_SEO_ARTICLES = [
  ...SEO_ARTICLES,
  ...SEO_ARTICLES_EXTRA,
  ...SEO_ARTICLES_AWAE,
]

export const SEO_ARTICLES_EXTRA2: Article[] = [
  // ── PLUS DE GUIDES PRATIQUES ──
  { slug: 'peinture-maison-cameroun', title: 'Repeindre sa maison au Cameroun — Guide et prix', description: 'Tout savoir sur la peinture intérieure et extérieure au Cameroun. Couleurs, prix et artisans.', category: 'guide-pratique', city: 'Cameroun', keywords: ['peinture maison cameroun', 'repeindre appartement cameroun', 'artisan peintre cameroun'] },
  { slug: 'plomberie-maison-cameroun', title: 'Plomberie à domicile au Cameroun — Trouver un artisan', description: "Comment trouver un bon plombier au Cameroun. Prix, conseils et entretien de la plomberie.", category: 'guide-pratique', city: 'Cameroun', keywords: ['plomberie cameroun', 'plombier yaoundé', 'réparation fuite eau cameroun'] },
  { slug: 'electricite-maison-cameroun', title: 'Installation électrique maison au Cameroun', description: "Guide complet sur l'installation et l'entretien électrique dans une maison au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['électricien cameroun', 'installation électrique maison cameroun', 'tableau électrique cameroun'] },
  { slug: 'toiture-maison-cameroun', title: 'Toiture maison au Cameroun — Entretien et réfection', description: 'Entretenir et rénover la toiture de sa maison au Cameroun. Types de toits et coûts.', category: 'guide-pratique', city: 'Cameroun', keywords: ['toiture maison cameroun', 'toit maison cameroun', 'réfection toiture cameroun'] },
  { slug: 'carrelage-appartement-cameroun', title: 'Carrelage et revêtement de sol au Cameroun', description: "Choisir le bon carrelage pour son appartement au Cameroun. Prix et tendances 2026.", category: 'guide-pratique', city: 'Cameroun', keywords: ['carrelage cameroun', 'revêtement sol cameroun', 'sol appartement cameroun'] },
  { slug: 'menuiserie-cameroun', title: 'Menuiserie et portes pour maison au Cameroun', description: "Choisir les bonnes portes et fenêtres pour sa maison au Cameroun. Artisans et prix.", category: 'guide-pratique', city: 'Cameroun', keywords: ['menuiserie cameroun', 'porte fenêtre cameroun', 'bois construction cameroun'] },
  { slug: 'climatisation-maison-cameroun', title: 'Climatisation pour maison au Cameroun — Guide 2026', description: "Installer un climatiseur chez soi au Cameroun. Marques, prix et entretien.", category: 'guide-pratique', city: 'Cameroun', keywords: ['climatisation cameroun', 'climatiseur maison cameroun', 'froid maison cameroun'] },
  { slug: 'piscine-villa-cameroun', title: 'Piscine pour villa au Cameroun — Coûts et entretien', description: "Installer et entretenir une piscine dans sa villa au Cameroun. Guide complet 2026.", category: 'guide-pratique', city: 'Cameroun', keywords: ['piscine villa cameroun', 'construction piscine cameroun', 'entretien piscine cameroun'] },
  { slug: 'demenagement-yaounde', title: 'Déménagement à Yaoundé — Trouver un transporteur', description: "Organiser son déménagement à Yaoundé. Transporteurs fiables et conseils pratiques.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['déménagement yaoundé', 'transporteur yaoundé', 'déménageur cameroun'] },
  { slug: 'demenagement-douala', title: 'Déménagement à Douala — Guide complet', description: "Tout savoir pour réussir son déménagement à Douala. Entreprises et tarifs.", category: 'guide-pratique', city: 'Douala', keywords: ['déménagement douala', 'transporteur douala', 'déménager douala cameroun'] },
  // ── QUARTIERS DOUALA SUPPLÉMENTAIRES ──
  { slug: 'appartement-bonaberi-douala', title: 'Appartement à Bonabéri Douala — Location 2026', description: "Location d'appartements à Bonabéri, sur la rive gauche du Wouri à Douala.", category: 'guide-quartier', city: 'Douala', neighborhood: 'Bonabéri', keywords: ['appartement bonabéri douala', 'location bonabéri', 'logement bonabéri douala'] },
  { slug: 'studio-ndog-passi-douala', title: 'Studio à Ndog-Passi Douala — Offres 2026', description: 'Studios et chambres disponibles à Ndog-Passi, Douala. Prix et contacts vérifiés.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Ndog-Passi', keywords: ['studio ndog-passi douala', 'location ndog-passi', 'logement ndog-passi douala'] },
  { slug: 'villa-sodiko-douala', title: 'Villa à Sodiko Douala — Résidentiel calme', description: 'Villas et appartements résidentiels à Sodiko, quartier calme de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Sodiko', keywords: ['villa sodiko douala', 'appartement sodiko', 'location sodiko douala'] },
  { slug: 'appartement-pk10-douala', title: 'Appartement à PK10 Douala — Location abordable', description: "Appartements et studios à PK10, quartier populaire aux abords de Douala.", category: 'guide-quartier', city: 'Douala', neighborhood: 'PK10', keywords: ['appartement pk10 douala', 'location pk10 douala', 'logement pk10'] },
  { slug: 'logement-yassa-douala', title: 'Logement à Yassa Douala — Zone industrielle et résidentielle', description: 'Appartements et maisons à Yassa, zone mixte industrielle et résidentielle de Douala.', category: 'guide-quartier', city: 'Douala', neighborhood: 'Yassa', keywords: ['logement yassa douala', 'appartement yassa', 'location yassa douala'] },
  // ── VILLES SUPPLÉMENTAIRES ──
  { slug: 'logement-foumban', title: 'Logement à Foumban — Capitale des arts', description: "Location et vente de logements à Foumban, capitale culturelle de l'Ouest Cameroun.", category: 'ville', city: 'Foumban', keywords: ['logement foumban', 'appartement foumban cameroun', 'location foumban'] },
  { slug: 'logement-dschang', title: 'Logement à Dschang — Ville universitaire', description: "Appartements et chambres étudiantes à Dschang, ville universitaire de l'Ouest Cameroun.", category: 'ville', city: 'Dschang', keywords: ['logement dschang', 'chambre étudiant dschang', 'location dschang cameroun'] },
  { slug: 'logement-kumba', title: 'Logement à Kumba — Sud-Ouest Cameroun', description: "Trouver un logement à Kumba, grande ville du Sud-Ouest Cameroun. Prix et disponibilités.", category: 'ville', city: 'Kumba', keywords: ['logement kumba cameroun', 'appartement kumba', 'location kumba'] },
  { slug: 'logement-edea', title: 'Logement à Edéa — Cité industrielle du Cameroun', description: "Location d'appartements et maisons à Edéa, ville industrielle du Littoral camerounais.", category: 'ville', city: 'Edéa', keywords: ['logement edea cameroun', 'appartement edea', 'location edea'] },
  { slug: 'logement-sangmelima', title: 'Logement à Sangmélima — Région du Sud', description: "Offres de logement à Sangmélima, capitale du Dja-et-Lobo au Cameroun.", category: 'ville', city: 'Sangmélima', keywords: ['logement sangmelima', 'appartement sangmelima cameroun', 'location sangmelima'] },
  { slug: 'logement-tibati', title: 'Logement à Tibati — Adamaoua Cameroun', description: "Trouver un logement à Tibati dans la région de l'Adamaoua au Cameroun.", category: 'ville', city: 'Tibati', keywords: ['logement tibati', 'appartement tibati cameroun', 'location tibati adamaoua'] },
  { slug: 'logement-meiganga', title: 'Logement à Meiganga — Est Cameroun', description: "Location et vente de logements à Meiganga, ville de l'Est Cameroun.", category: 'ville', city: 'Meiganga', keywords: ['logement meiganga', 'appartement meiganga cameroun', 'location meiganga'] },
  { slug: 'logement-batouri', title: 'Logement à Batouri — Région de l\'Est', description: "Offres de logement à Batouri, dans la région de l'Est Cameroun.", category: 'ville', city: 'Batouri', keywords: ['logement batouri', 'appartement batouri cameroun', 'location batouri'] },
  { slug: 'logement-nkongsamba', title: 'Logement à Nkongsamba — Littoral Cameroun', description: "Location d'appartements et maisons à Nkongsamba, grande ville du Moungo.", category: 'ville', city: 'Nkongsamba', keywords: ['logement nkongsamba', 'appartement nkongsamba cameroun', 'location nkongsamba'] },
  { slug: 'logement-wum', title: 'Logement à Wum — Nord-Ouest Cameroun', description: "Trouver un logement à Wum dans le Nord-Ouest du Cameroun.", category: 'ville', city: 'Wum', keywords: ['logement wum cameroun', 'appartement wum', 'location wum nord-ouest'] },
  // ── TENDANCES ET MARCHÉ SUPPLÉMENTAIRES ──
  { slug: 'boom-immobilier-yaounde', title: 'Le boom immobilier de Yaoundé — Analyse 2026', description: "Pourquoi l'immobilier à Yaoundé connaît une croissance exceptionnelle en 2026.", category: 'marche', city: 'Yaoundé', keywords: ['boom immobilier yaoundé', 'croissance immobilier yaoundé', 'marché immobilier yaoundé 2026'] },
  { slug: 'prix-metre-carre-yaounde', title: 'Prix au mètre carré à Yaoundé — 2026', description: "Combien coûte le mètre carré à Yaoundé selon les quartiers ? Notre analyse complète.", category: 'marche', city: 'Yaoundé', keywords: ['prix mètre carré yaoundé', 'coût m2 yaoundé', 'prix immobilier m2 yaoundé 2026'] },
  { slug: 'prix-metre-carre-douala', title: 'Prix au mètre carré à Douala — 2026', description: "Analyse des prix au mètre carré dans les différents quartiers de Douala en 2026.", category: 'marche', city: 'Douala', keywords: ['prix mètre carré douala', 'coût m2 douala', 'prix immobilier douala 2026'] },
  { slug: 'immobilier-vert-cameroun', title: 'Immobilier vert et durable au Cameroun — Tendances', description: "Les constructions écologiques et durables au Cameroun. Une tendance qui se confirme en 2026.", category: 'marche', city: 'Cameroun', keywords: ['immobilier vert cameroun', 'construction durable cameroun', 'logement écologique cameroun'] },
  { slug: 'habitat-social-cameroun', title: "L'habitat social au Cameroun — Politiques et réalités", description: "L'état du logement social au Cameroun. Programmes gouvernementaux et perspectives.", category: 'marche', city: 'Cameroun', keywords: ['habitat social cameroun', 'logement social cameroun', 'SIC cameroun'] },
  { slug: 'promotion-immobiliere-cameroun', title: 'Promoteurs immobiliers au Cameroun — Guide 2026', description: "Les principaux promoteurs immobiliers au Cameroun. Projets, prix et fiabilité.", category: 'marche', city: 'Cameroun', keywords: ['promoteur immobilier cameroun', 'promotion immobilière cameroun', 'constructeur logement cameroun'] },
  { slug: 'residence-fermee-yaounde', title: 'Résidences fermées à Yaoundé — Sécurité et confort', description: "Les résidences sécurisées et fermées à Yaoundé. Guide des meilleures adresses.", category: 'marche', city: 'Yaoundé', keywords: ['résidence fermée yaoundé', 'logement sécurisé yaoundé', 'résidence gardée yaoundé'] },
  { slug: 'residence-fermee-douala', title: 'Résidences fermées à Douala — Les meilleures adresses', description: "Résidences sécurisées et gated communities à Douala. Guide complet 2026.", category: 'marche', city: 'Douala', keywords: ['résidence fermée douala', 'logement sécurisé douala', 'gated community douala'] },
  { slug: 'renovation-ancienne-maison-cameroun', title: 'Rénover une ancienne maison au Cameroun — Guide', description: "Acheter et rénover une ancienne maison au Cameroun. Coûts, étapes et pièges à éviter.", category: 'marche', city: 'Cameroun', keywords: ['rénovation maison cameroun', 'rénover ancienne maison cameroun', 'travaux rénovation cameroun'] },
  { slug: 'achat-appartement-plan-cameroun', title: 'Acheter un appartement sur plan au Cameroun', description: "Comment acheter un bien immobilier sur plan au Cameroun. Avantages, risques et garanties.", category: 'marche', city: 'Cameroun', keywords: ['achat appartement sur plan cameroun', 'vente sur plan cameroun', 'VEFA cameroun'] },
  { slug: 'immobilier-digital-cameroun', title: 'L\'immobilier digital au Cameroun — La révolution Habynex', description: "Comment le numérique transforme l'immobilier au Cameroun. Plateformes et innovations.", category: 'marche', city: 'Cameroun', keywords: ['immobilier digital cameroun', 'proptech cameroun', 'technologie immobilier cameroun'] },
  // ── HABYNEX SUPPLÉMENTAIRES ──
  { slug: 'habynex-quartiers-couverts', title: 'Tous les quartiers couverts par Habynex à Yaoundé', description: "Découvrez tous les quartiers de Yaoundé et leurs alentours où Habynex propose des annonces vérifiées.", category: 'habynex', city: 'Yaoundé', keywords: ['quartiers habynex yaoundé', 'zones habynex', 'couverture habynex yaoundé'] },
  { slug: 'habynex-propriétaires', title: 'Habynex pour les propriétaires — Mettre son bien en ligne', description: "Comment les propriétaires camerounais publient leurs biens sur Habynex et trouvent des locataires fiables.", category: 'habynex', city: 'Cameroun', keywords: ['habynex propriétaire', 'publier annonce habynex', 'trouver locataire habynex cameroun'] },
  { slug: 'habynex-application-mobile', title: 'Application mobile Habynex — Tout l\'immobilier dans votre poche', description: "L'application Habynex disponible sur Android et iOS. Cherchez un logement depuis votre smartphone.", category: 'habynex', city: 'Cameroun', keywords: ['application habynex android', 'app habynex ios', 'habynex smartphone cameroun'] },
  { slug: 'habynex-notifications-alertes', title: 'Alertes et notifications Habynex — Ne ratez aucune annonce', description: "Activez les alertes Habynex pour être informé en temps réel des nouvelles annonces selon vos critères.", category: 'habynex', city: 'Cameroun', keywords: ['alerte habynex', 'notification nouvelle annonce cameroun', 'habynex alerte logement'] },
]

// Mise à jour ALL_SEO_ARTICLES
export const ALL_SEO_ARTICLES_FINAL = [
  ...SEO_ARTICLES,
  ...SEO_ARTICLES_EXTRA,
  ...SEO_ARTICLES_AWAE,
  ...SEO_ARTICLES_EXTRA2,
]

export const SEO_ARTICLES_FINAL_BATCH: Article[] = [
  { slug: 'louer-court-sejour-yaounde', title: 'Location court séjour à Yaoundé — Airbnb et alternatives', description: "Trouver une location courte durée à Yaoundé. Alternatives locales à Airbnb.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['court séjour yaoundé', 'location vacances yaoundé', 'airbnb yaoundé'] },
  { slug: 'louer-court-sejour-douala', title: 'Location court séjour à Douala — Guide 2026', description: "Location meublée courte durée à Douala pour voyageurs d'affaires et touristes.", category: 'guide-pratique', city: 'Douala', keywords: ['court séjour douala', 'location vacances douala', 'hébergement temporaire douala'] },
  { slug: 'meilleur-quartier-vivre-yaounde', title: 'Quel est le meilleur quartier pour vivre à Yaoundé ?', description: "Notre classement des meilleurs quartiers pour vivre à Yaoundé selon le budget et le style de vie.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['meilleur quartier yaoundé', 'où vivre yaoundé', 'classement quartier yaoundé'] },
  { slug: 'meilleur-quartier-vivre-douala', title: 'Quel est le meilleur quartier pour vivre à Douala ?', description: "Classement des meilleurs quartiers de Douala selon la qualité de vie, la sécurité et les prix.", category: 'guide-pratique', city: 'Douala', keywords: ['meilleur quartier douala', 'où vivre douala', 'classement quartier douala'] },
  { slug: 'appartement-moderne-yaounde', title: 'Appartements modernes à Yaoundé — Nouvelles constructions', description: "Les appartements neufs et modernes disponibles à Yaoundé. Standing et équipements récents.", category: 'marche', city: 'Yaoundé', keywords: ['appartement moderne yaoundé', 'neuf yaoundé', 'résidence moderne yaoundé'] },
  { slug: 'quartier-calme-yaounde', title: 'Les quartiers les plus calmes de Yaoundé — 2026', description: "Quel quartier choisir pour la tranquillité à Yaoundé ? Notre sélection des zones résidentielles calmes.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['quartier calme yaoundé', 'zone résidentielle calme yaoundé', 'vivre tranquille yaoundé'] },
  { slug: 'quartier-animé-yaounde', title: 'Les quartiers les plus animés de Yaoundé', description: "Vibrer au rythme de Yaoundé : les quartiers les plus dynamiques et vivants de la capitale.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['quartier animé yaoundé', 'vie nocturne yaoundé', 'sortir yaoundé quartier'] },
  { slug: 'fete-voisin-cameroun', title: 'La vie de voisinage au Cameroun — Traditions et modernité', description: "La solidarité entre voisins au Cameroun. Traditions, droits et obligations du bon voisinage.", category: 'guide-pratique', city: 'Cameroun', keywords: ['voisinage cameroun', 'relation voisin cameroun', 'solidarité quartier cameroun'] },
  { slug: 'droit-propriete-cameroun', title: "Droit de propriété au Cameroun — Ce que dit la loi", description: "Les droits et obligations des propriétaires immobiliers au Cameroun. Guide juridique complet.", category: 'guide-pratique', city: 'Cameroun', keywords: ['droit propriété cameroun', 'propriétaire immobilier cameroun', 'loi propriété cameroun'] },
  { slug: 'succession-immobiliere-cameroun', title: "Succession et héritage immobilier au Cameroun", description: "Comment gérer la succession d'un bien immobilier au Cameroun. Démarches et droits des héritiers.", category: 'guide-pratique', city: 'Cameroun', keywords: ['succession immobilière cameroun', 'héritage maison cameroun', 'partage bien immobilier cameroun'] },
  { slug: 'copropriete-cameroun', title: "La copropriété au Cameroun — Droits et obligations", description: "Vivre en copropriété au Cameroun : règles, charges et gestion des parties communes.", category: 'guide-pratique', city: 'Cameroun', keywords: ['copropriété cameroun', 'charges copropriété cameroun', 'règlement copropriété cameroun'] },
  { slug: 'syndic-immeuble-cameroun', title: "Syndic d'immeuble au Cameroun — Rôle et fonctions", description: "Le rôle du syndic dans la gestion d'un immeuble au Cameroun. Obligations et droits.", category: 'guide-pratique', city: 'Cameroun', keywords: ['syndic immeuble cameroun', 'gestionnaire immeuble cameroun', 'syndic copropriété cameroun'] },
  { slug: 'permis-construire-cameroun', title: "Obtenir un permis de construire au Cameroun", description: "Tout savoir sur le permis de construire au Cameroun. Démarches, délais et coûts.", category: 'guide-pratique', city: 'Cameroun', keywords: ['permis construire cameroun', 'autorisation construction cameroun', 'démarche permis bâtir cameroun'] },
  { slug: 'architecte-cameroun', title: "Choisir un architecte au Cameroun — Guide 2026", description: "Comment choisir un bon architecte pour votre projet immobilier au Cameroun. Critères et tarifs.", category: 'guide-pratique', city: 'Cameroun', keywords: ['architecte cameroun', 'cabinet architecture cameroun', 'plan maison architecte cameroun'] },
  { slug: 'geometre-cameroun', title: "Le géomètre expert au Cameroun — Quand et pourquoi y recourir", description: "Le rôle du géomètre expert au Cameroun dans les transactions immobilières. Bornage et cadastre.", category: 'guide-pratique', city: 'Cameroun', keywords: ['géomètre cameroun', 'bornage terrain cameroun', 'cadastre cameroun'] },
  { slug: 'notaire-immobilier-cameroun', title: "Le notaire et l'immobilier au Cameroun", description: "Le rôle du notaire dans les transactions immobilières au Cameroun. Actes et frais de notaire.", category: 'guide-pratique', city: 'Cameroun', keywords: ['notaire immobilier cameroun', 'acte notarié cameroun', 'frais notaire cameroun'] },
  { slug: 'habitat-rural-cameroun', title: "L'habitat rural au Cameroun — Spécificités et opportunités", description: "L'immobilier en zone rurale au Cameroun. Particularités, droits coutumiers et investissements.", category: 'marche', city: 'Cameroun', keywords: ['habitat rural cameroun', 'immobilier campagne cameroun', 'terrain rural cameroun'] },
  { slug: 'parkings-yaounde', title: "Stationnement et parking à Yaoundé — Par quartier", description: "La problématique du stationnement à Yaoundé. Quartiers avec parking et solutions.", category: 'guide-pratique', city: 'Yaoundé', keywords: ['parking yaoundé', 'stationnement yaoundé', 'voiture appartement yaoundé'] },
  { slug: 'accessibilite-pmr-cameroun', title: "Accessibilité PMR dans les logements au Cameroun", description: "L'accessibilité pour les personnes à mobilité réduite dans les logements camerounais.", category: 'guide-pratique', city: 'Cameroun', keywords: ['accessibilité PMR cameroun', 'handicap logement cameroun', 'rampe accès maison cameroun'] },
  { slug: 'bruit-voisinage-cameroun', title: "Gérer les nuisances sonores dans son logement au Cameroun", description: "Bruit de voisinage au Cameroun : vos droits, recours et solutions amiables.", category: 'guide-pratique', city: 'Cameroun', keywords: ['bruit voisinage cameroun', 'nuisance sonore logement cameroun', 'tapage nocturne cameroun'] },
  { slug: 'humidite-moisissures-maison-cameroun', title: "Humidité et moisissures dans les maisons au Cameroun", description: "Comment lutter contre l'humidité et les moisissures dans votre logement au Cameroun.", category: 'guide-pratique', city: 'Cameroun', keywords: ['humidité maison cameroun', 'moisissure logement cameroun', 'traitement humidité cameroun'] },
]
